name: "Cronjob"
on:
  schedule:
    - cron: "15 * * * *"
  workflow_dispatch:

jobs:
  update-weather:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Generate README
        uses: huantt/weather-forecast@v1.0.5
        with:
          city: Évreux
          days: 3
          weather-api-key: ${{ secrets.WEATHER_API_KEY }}
          template-file: "templates/README.md.template"
          out-file: "README.md"
      - name: Commit
        run: |
          if git diff --exit-code; then
            echo "No changes to commit."
            exit 0
          else
            git config user.name github-actions
            git config user.email github-actions@github.com
            git add .
            git commit -m "Updated weather"
            git push origin main
          fi
